name    'saz-resolv_conf'
version '3.0.0'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage /etc/resolv.conf with puppet'
dependency 'puppetlabs/stdlib', '>= 0.1.6'
project_page 'https://github.com/saz/puppet-resolv_conf'
