name    'saz-resolv_conf'
version '1.0.0'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage resolv.conf via Puppet'
project_page 'https://github.com/saz/puppet-resolv_conf'
dependency 'saz/dnsmasq', '>= 1.0.0'
